name: publish
env:
  CLI: true
# masterブランチにpushした時のみ実行するワークフロー
on:
  push:
    branches:
      - master
    tags:
      - "!*"

jobs:
  release:
    name: Setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./UnityStereoCameraManager/Assets/Plugins/StereoCameraManager
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: "https://npm.pkg.github.com"
      # まだpublishされていないバージョンならpublishする
      - name: publish
        run: |
          npm publish || echo "Does not publish"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
